package com.example.pankaj.astegicdemo.Database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONTACTS_DATA".
*/
public class ContactsDataDao extends AbstractDao<ContactsData, Long> {

    public static final String TABLENAME = "CONTACTS_DATA";

    /**
     * Properties of entity ContactsData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Contacts_id = new Property(1, int.class, "contacts_id", false, "CONTACTS_ID");
        public final static Property ContactId = new Property(2, String.class, "contactId", false, "CONTACT_ID");
        public final static Property StagingId = new Property(3, String.class, "stagingId", false, "STAGING_ID");
    }


    public ContactsDataDao(DaoConfig config) {
        super(config);
    }
    
    public ContactsDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONTACTS_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CONTACTS_ID\" INTEGER NOT NULL ," + // 1: contacts_id
                "\"CONTACT_ID\" TEXT," + // 2: contactId
                "\"STAGING_ID\" TEXT);"); // 3: stagingId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONTACTS_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ContactsData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getContacts_id());
 
        String contactId = entity.getContactId();
        if (contactId != null) {
            stmt.bindString(3, contactId);
        }
 
        String stagingId = entity.getStagingId();
        if (stagingId != null) {
            stmt.bindString(4, stagingId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ContactsData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getContacts_id());
 
        String contactId = entity.getContactId();
        if (contactId != null) {
            stmt.bindString(3, contactId);
        }
 
        String stagingId = entity.getStagingId();
        if (stagingId != null) {
            stmt.bindString(4, stagingId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ContactsData readEntity(Cursor cursor, int offset) {
        ContactsData entity = new ContactsData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // contacts_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // contactId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // stagingId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ContactsData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setContacts_id(cursor.getInt(offset + 1));
        entity.setContactId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStagingId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ContactsData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ContactsData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ContactsData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
