package com.example.pankaj.astegicdemo.Database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EXTENSIONS_DATA".
*/
public class ExtensionsDataDao extends AbstractDao<ExtensionsData, Long> {

    public static final String TABLENAME = "EXTENSIONS_DATA";

    /**
     * Properties of entity ExtensionsData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Context = new Property(1, String.class, "context", false, "CONTEXT");
        public final static Property PhoneContactId = new Property(2, int.class, "phoneContactId", false, "PHONE_CONTACT_ID");
    }


    public ExtensionsDataDao(DaoConfig config) {
        super(config);
    }
    
    public ExtensionsDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EXTENSIONS_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CONTEXT\" TEXT," + // 1: context
                "\"PHONE_CONTACT_ID\" INTEGER NOT NULL );"); // 2: phoneContactId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EXTENSIONS_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ExtensionsData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String context = entity.getContext();
        if (context != null) {
            stmt.bindString(2, context);
        }
        stmt.bindLong(3, entity.getPhoneContactId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ExtensionsData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String context = entity.getContext();
        if (context != null) {
            stmt.bindString(2, context);
        }
        stmt.bindLong(3, entity.getPhoneContactId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ExtensionsData readEntity(Cursor cursor, int offset) {
        ExtensionsData entity = new ExtensionsData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // context
            cursor.getInt(offset + 2) // phoneContactId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ExtensionsData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setContext(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPhoneContactId(cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ExtensionsData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ExtensionsData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ExtensionsData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
